name: 'Create changelog'
description: 'Create a post in changes.page'
inputs:
  page_secret:
    description: 'Page integration secret from changes.page'
    required: true
  post_title:
    description: 'Title of the post'
    required: true
  post_content:
    description: 'Content of the post'
    required: true
  post_type:
    description: "Type of the post, can be 'fix', 'new', 'improvement', 'announcement' or 'alert'"
    default: 'new'
  post_status:
    description: "Type of the post, can be 'draft' or 'published'"
    default: 'draft'
runs:
  using: 'node16'
  main: 'dist/index.js'
